//!  — generated / vendored file detection: which HEAD files are NOT
//! hand-authored code in this repo (build output, tool-emitted code, checked-in
//! dependencies). The base of "count only human-authored code" — so a 40k-line
//! lockfile or a `vendor/` tree doesn't skew ownership, churn and hotspot signals.
//!
//! Path-based and deterministic: the low-false-positive subset of GitHub
//! Linguist's generated + vendored heuristics (the rules that need no content
//! read). Content-marker detection (`@generated`, `DO NOT EDIT`) is deferred.
//! Heuristic by design (git has no ground truth for "is generated"), so the bench
//! check is DEFINITIONAL: the table must equal this rule applied to the HEAD paths.
//!
//! Content markers (, mid+): a second source that catches generated
//! files the PATH rules miss — a hand-named `.ts` that a codegen tool emitted with
//! a `@generated` / `Code generated by … DO NOT EDIT` header. Reads the first lines
//! of each HEAD text blob (so mid+ tier). Path detection wins when both fire (it's
//! cheaper and tier-independent), so content markers only ADD files.

use std::path::Path;

use anyhow::Result;

/// Checked-in dependency directories (Linguist "vendored"). A match on any path
/// segment classifies the file as vendored.
const VENDORED_DIRS: &[&str] = &[
    "node_modules",
    "bower_components",
    "vendor",
    "vendored",
    "third_party",
    "third-party",
    "Godeps",
];

/// Tool-emitted lockfiles (exact basenames). Generated from a manifest, never
/// hand-edited.
const LOCKFILES: &[&str] = &[
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "poetry.lock",
    "Pipfile.lock",
    "Gemfile.lock",
    "composer.lock",
    "go.sum",
    "flake.lock",
];

/// If `path` is generated or vendored, return (category, the rule that matched).
/// Vendored is checked first: a lockfile inside `node_modules/` is vendored, not a
/// first-party generated artifact. Rules are ordered most-specific first.
pub fn classify(path: &str) -> Option<(&'static str, &'static str)> {
    // Vendored: any path segment is a known dependency directory.
    if path.split('/').any(|seg| VENDORED_DIRS.contains(&seg)) {
        return Some(("vendored", "vendored-dir"));
    }

    let base = path.rsplit('/').next().unwrap_or(path);

    // Generated: exact lockfile basenames.
    if LOCKFILES.contains(&base) {
        return Some(("generated", "lockfile"));
    }
    // Minified assets.
    if base.ends_with(".min.js") || base.ends_with(".min.css") {
        return Some(("generated", "minified"));
    }
    // Source maps.
    if base.ends_with(".map") {
        return Some(("generated", "sourcemap"));
    }
    // Jest / Vitest snapshots.
    if base.ends_with(".snap") {
        return Some(("generated", "snapshot"));
    }
    // Protobuf / gRPC codegen.
    if base.ends_with(".pb.go")
        || base.ends_with(".pb.cc")
        || base.ends_with(".pb.h")
        || base.ends_with("_pb2.py")
        || base.ends_with("_pb2_grpc.py")
    {
        return Some(("generated", "protobuf"));
    }
    // Codegen marked in the filename itself.
    if base.contains(".generated.")
        || base.ends_with(".g.dart")
        || base.ends_with(".freezed.dart")
        || base.ends_with(".designer.cs")
        || base.ends_with(".g.cs")
    {
        return Some(("generated", "codegen-name"));
    }
    None
}

/// Codegen header markers (lowercased). Matched at the START of a comment line —
/// after stripping the comment leader — NOT anywhere in the line. Real headers put
/// the marker first (`// Code generated by …`, `// @generated`, `# Auto-generated`),
/// while a hand-written file that merely mentions "@generated" or "auto-generated"
/// in prose has it mid-sentence, so the anchor keeps those out. That precision is
/// the whole point: a false "generated" flag would wrongly drop a real file from
/// ownership.
const CONTENT_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "autogenerated",
    "auto-generated",
    "automatically generated",
];

/// How many leading lines to scan — codegen headers live at the very top.
const HEAD_LINES: usize = 15;

/// Leading characters a comment can open with (whitespace + comment punctuation).
/// Stripping them leaves the comment's actual text, so a marker at the start of
/// that text anchors the match. Kept in sync with the bench's git-grep regex.
const COMMENT_LEAD: &[char] = &[' ', '\t', '/', '*', '#', '!', '-', '<', '>', ';', '%'];

fn is_binary(bytes: &[u8]) -> bool {
    bytes[..bytes.len().min(8000)].contains(&0)
}

/// Does the file's header carry a generated marker? Scans the first `HEAD_LINES`
/// lines: strip the comment leader, then test whether the remaining text STARTS
/// WITH a marker (case-insensitive).
pub fn has_content_marker(bytes: &[u8]) -> bool {
    if is_binary(bytes) {
        return false;
    }
    let text = String::from_utf8_lossy(bytes);
    for line in text.lines().take(HEAD_LINES) {
        let content = line.trim_start_matches(COMMENT_LEAD).to_ascii_lowercase();
        if CONTENT_MARKERS.iter().any(|m| content.starts_with(m)) {
            return true;
        }
    }
    false
}

/// HEAD text files whose header carries a generated marker (paths only; the caller
/// drops any already flagged by a path rule and stitches file_ids). mid+ tier.
/// Parallelized over HEAD blobs (order-preserving, so identical output).
pub fn compute_content(repo_path: &Path) -> Result<Vec<String>> {
    crate::blame::par_head_blobs(repo_path, |path, data| {
        if has_content_marker(data) {
            vec![path.to_string()]
        } else {
            Vec::new()
        }
    })
}

#[cfg(test)]
mod tests {
    use super::{classify, has_content_marker};

    #[test]
    fn content_markers_match_headers_at_line_start() {
        // Real codegen headers: marker right after the comment leader.
        assert!(has_content_marker(b"// @generated by thrift\npackage x;\n"));
        assert!(has_content_marker(b"//@generated\n"));
        assert!(has_content_marker(b"// Code generated by protoc. DO NOT EDIT.\n"));
        assert!(has_content_marker(b"# Auto-generated by openapi-gen\n"));
        assert!(has_content_marker(b" * Automatically generated - do not edit\n")); // JSDoc continuation
        // Marker must be near the top, not buried deep in the file.
        let mut deep = String::new();
        for _ in 0..40 { deep.push_str("real code line\n"); }
        deep.push_str("// @generated\n");
        assert!(!has_content_marker(deep.as_bytes()));
        // PROSE mentions are NOT flagged — the marker is mid-line, not at the start.
        // (These are the real eos false positives the anchor rule kills.)
        assert!(!has_content_marker(b"//! Content-marker detection (`@generated`) is deferred.\n"));
        assert!(!has_content_marker(b"-- Pro+ feature - auto-generated at the end of each sprint.\n"));
        assert!(!has_content_marker(b"fn main() { println!(\"hi\"); }\n"));
        assert!(!has_content_marker(&[0u8, 1, 2, b'@', b'g']));  // binary
    }


    #[test]
    fn vendored_dirs_match_any_segment() {
        assert_eq!(classify("node_modules/react/index.js"), Some(("vendored", "vendored-dir")));
        assert_eq!(classify("eng/web/vendor/lib.js"), Some(("vendored", "vendored-dir")));
        assert_eq!(classify("third_party/x/y.c"), Some(("vendored", "vendored-dir")));
        // A lockfile inside a vendored dir is vendored, not "lockfile".
        assert_eq!(classify("node_modules/foo/package-lock.json"), Some(("vendored", "vendored-dir")));
    }

    #[test]
    fn generated_by_name() {
        assert_eq!(classify("package-lock.json"), Some(("generated", "lockfile")));
        assert_eq!(classify("eng/web/pnpm-lock.yaml"), Some(("generated", "lockfile")));
        assert_eq!(classify("Cargo.lock"), Some(("generated", "lockfile")));
        assert_eq!(classify("static/app.min.js"), Some(("generated", "minified")));
        assert_eq!(classify("static/app.css.map"), Some(("generated", "sourcemap")));
        assert_eq!(classify("api/service.pb.go"), Some(("generated", "protobuf")));
        assert_eq!(classify("proto/user_pb2.py"), Some(("generated", "protobuf")));
        assert_eq!(classify("src/models.generated.ts"), Some(("generated", "codegen-name")));
        assert_eq!(classify("__snapshots__/App.test.tsx.snap"), Some(("generated", "snapshot")));
    }

    #[test]
    fn hand_authored_is_none() {
        assert_eq!(classify("eng/gitindex/src/main.rs"), None);
        assert_eq!(classify("go.mod"), None); // authored, unlike go.sum
        assert_eq!(classify("package.json"), None); // authored, unlike the lockfile
        assert_eq!(classify("src/vendored.ts"), None); // a filename, not a dir segment
        assert_eq!(classify("src/map.ts"), None); // not a .map file
    }
}
